[package]
name = "Strike Binds"
description = "Bind buttons directly to each attack type."
repository = "https://github.com/Petethegoat/strike-binds"
authors = [ "Pete Goodfellow",]
version = "1.0.0"

[dependencies]
assets = [ "MWSE\\mods\\Strike Binds",]

[dependencies.mwse]
buildnumber = 4093
